
public class six {
	static void f1(){
		try {
			System.out.println("inside fone");
			throw new RuntimeException("demo");
		}
		finally {
			System.out.println("fone is over");
		}
	}
	
	static void f2() {
		try {
			System.out.println("inside ftwo ");
			return;
		}
		finally {
			System.out.println("ftwo is over ");
		}
	}
	
	static void f3() {
		try {
			System.out.println("inside fthree");
		}
		finally {
			System.out.println("fthree is over....");
		}
	}
	
	
	public static void main(String[] args) {
		try {
			f1();
		}
		catch(Exception e) {
			System.out.println("exception has been caught");
		}
	
	f2();
	f3();

	}
}
